homeassistant:
  # Home Assistant 正在运行的位置的名称
  name: Lukin Home
  # Home Assistant 所在的经纬度，计算太阳升起和落下的时间
  # 最好通过手机，下载GPS相关软件，获取经纬度信息
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # 影响天气/日出数据（海拔高度以米为单位）
  elevation: !secret homeassistant_elevation
  # 工制：metric, 英制：imperial
  unit_system: metric
  # 从这里找到你的时区: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # 自定义文件
  customize: !include_dir_merge_named customize
  # See: https://home-assistant.io/docs/configuration/customizing-devices/
  customize_domain:
    automation:
      initial_state: on

  customize_glob:
    "device_tracker.*":
      hidden: true
      homebridge_hidden: true

    "group.all_*":
      homebridge_hidden: true

    group.temperature:
      state_card_mode: badges

# 启用前端
frontend:
  javascript_version: latest

# 启用配置界面
config:

# 检查可用的更新
updater:
  include_used_components: true

http:
  base_url: !secret http_base_url
  # 变量定义在secrets.yaml文件
  api_password: !secret http_api_password
  # SSL证书配置
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key

# 自动发现一些设备
discovery:

# 启用显示跟踪设备位置的地图
map:

# 跟踪太阳
sun:

# 激活iOS客户端
ios:

# ifttt
ifttt:
  key: !secret ifttt_key

# 文字转语音
tts:
  # https://cloud.baidu.com/doc/SPEECH/TTS-API.html#.F4.00.0F.EC.58.FB.9F.62.9F.DC.6F.A3.F5.68.98.DD
  - platform: baidu
    app_id: !secret tts_bd_app_id
    api_key: !secret tts_bd_api_key
    secret_key: !secret tts_bd_secret_key
    # 速度 0 - 9
    speed: 5
    # 音调 0 - 9
    pitch: 5
    # 音量 0 - 15
    volume: 15
    # 人 0,1,3,4
    person: 0

  # https://cloud.google.com/speech/docs/languages
  - platform: google

# 媒体播放器
media_player:
  # 激活vlc
  - platform: vlc
    name: speaker_vlc
    arguments:  --alsa-audio-device=hw:0
    # 扫描间隔1s，要不然状态反馈不及时，导致其他地方获取状态不正常。
    scan_interval: 1

# MQTT
mqtt:
  embedded:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-Lukin
  username: !secret mqtt_username
  password: !secret mqtt_password


# 记录 Home Assistant 的运行日志
logger:
  # 可能的日志严重程度是: notset, debug, info, warn, warning, error, fatal, critical
  default: info
  logs:
    homeassistant.core: error
    homeassistant.components.automation: warn
    homeassistant.components.device_tracker: error
    homeassistant.components.discovery: warn
    homeassistant.components.http: warn
    homeassistant.components.media_player: info
    homeassistant.components.recorder: error
    homeassistant.helpers.script: info
    homeassistant.helpers.entity: critical
    homeassistant.exceptions: info

# 记录到数据库中，有 history 和 logbook 去处理
recorder:
  purge_interval: 1
  purge_keep_days: 365
  exclude:
    domains:
      - updater
      - automation
      - device_tracker
    entities:
      - sun.sun
      - sensor.moji_weather
      - sensor.ubuntu_pre_volume
      - sensor.date
      - sensor.time

# 记录事件，按照时间顺序显示房屋发生的所有变化
logbook:

# 支持随着时间的推移跟踪状态变化
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover

  exclude:
    entities:
      - sun.sun
      - sensor.moji_weather
      - sensor.ubuntu_pre_volume
      - sensor.date
      - sensor.time

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
shell_command: !include_dir_merge_named shell_command

panel_iframe:
  router:
    title: 'HiWiFi'
    icon: mdi:router-wireless
    url: 'http://192.168.199.1'

  aria2:
    title: 'Aria2'
    icon: mdi:cloud-download
    url: 'http://down.lukin.cn/'

  printer:
    title: 'Printer'
    icon: mdi:printer
    url: 'http://192.168.199.8:631'